HARD_METRICS = {
    "FINAL_DOC_CLAIM_WITHOUT_ACCEPTED_EVIDENCE",
    "FRAMEWORK_RELEASE_MISSTATED_AS_PROJECT_ACTIVATION",
    "CON002_SILENTLY_RESOLVED",
    "PILOT_DOT_BANYAN_SILENTLY_PROMOTED",
    "BOOTSTRAP_WORKSPACE_BLIND_DELETION",
    "VERSION_POINTER_SILENT_TRANSITION",
    "LEGACY_DOC_PHYSICAL_MIGRATION_EXECUTED",
    "CURRENT_PROJECT_GIT_MUTATION",
    "SECRET_BODY_EXPOSURE_IN_DOCS",
    "GENERIC_DOC_PROJECT_LITERAL_LEAK",
}
def validate(metrics):
    assert set(metrics) == HARD_METRICS
    assert all(v == 0 for v in metrics.values())
if __name__ == "__main__":
    validate({k:0 for k in HARD_METRICS})
    print("PASS Stage20 conformance spec")
